//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class cargo_laboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cargo_laboral()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int ID_CARGO_LABORAL { get; set; }
        [Display(Name = "Cargo Laboral")]
        public string CARGO_LABORAL1 { get; set; }
        [Display(Name = "Descripcion")]
        public string DESCRIPCION_CARGO_LABORAL { get; set; }
        [Display(Name = "Salario")]
        public Nullable<float> SALARIO_MENSUAL_CARGO_LABORAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
