//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.factura_producto = new HashSet<factura_producto>();
        }
    
        public int ID_FACTURA { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> FECHA_FACTURA { get; set; }
        [Display(Name = "Sucursal")]
        public Nullable<int> ID_SUCURSAL_FACTURA { get; set; }
        [Display(Name = "Cliente")]
        public Nullable<int> ID_CLIENTE_FACTURA { get; set; }
        [Display(Name = "Empleado")]
        public Nullable<int> ID_EMPLEADO_FACTURA { get; set; }
        [Display(Name = "Total")]
        public Nullable<float> PRECIO_TOTAL { get; set; }
        [Display(Name = "Numero Comprobante")]
        public string NUMERO_COMPROBANTE { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual empleado empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_producto> factura_producto { get; set; }
        public virtual sucursal sucursal { get; set; }        
    }
}
