//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class factura_producto
    {
        public int ID_FACTURA { get; set; }
        [Display(Name = "Producto")]
        public int ID_PRODUCTO { get; set; }
        public int ID_FACPROD { get; set; }
        [Display(Name = "Precio Total")]
        public Nullable<float> PRECIO_TOTAL_PRODUCTO { get; set; }
        [Display(Name = "Cantidad Producto")]
        public Nullable<int> CANTIDAD_PRODUCTO { get; set; }
    
        public virtual factura factura { get; set; }
        public virtual producto producto { get; set; }
        public string Estado { get; set; }
    }
}
