//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.cliente = new HashSet<cliente>();
            this.empleado = new HashSet<empleado>();
            this.telefono = new HashSet<telefono>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int ID_PERSONA { get; set; }
        [Display(Name = "Primer Nombre")]
        public string PRIMER_NOMBRE_PERSONA { get; set; }
        [Display(Name = "Segundo Nombre")]
        public string SEGUNDO_NOMBRE_PERSONA { get; set; }
        [Display(Name = "Primer Apellido")]
        public string PRIMER_APELLIDO_PERSONA { get; set; }
        [Display(Name = "Segundo Apellido")]
        public string SEGUNDO_APELLIDO_PERSONA { get; set; }
        [Display(Name = "Fecha de Nacimiento")]
        public Nullable<System.DateTime> FECHA_NACIMIENTO_PERSONA { get; set; }
        [Display(Name = "Numero Identidad")]
        public string NUMERO_IDENTIDAD_PERSONA { get; set; }
        [Display(Name = "Direccion")]
        public string DIRECCION_RESIDENCIA_PERSONA { get; set; }
        [Display(Name = "Ciudad")]
        public Nullable<int> ID_CIUDAD_RESIDENCIA_PERSONA { get; set; }
        [Display(Name = "Sexo")]
        public Nullable<int> ID_SEXO_PERSONA { get; set; }
    
        public virtual ciudad ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente> cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<telefono> telefono { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual sexo sexo { get; set; }
    }
}
