//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.factura_producto = new HashSet<factura_producto>();
            this.producto_proveedor = new HashSet<producto_proveedor>();
        }
    
        public int ID_PRODUCTO { get; set; }
        [Display(Name = "Nombre Producto")]
        public string NOMBRE_PRODUCTO { get; set; }
        [Display(Name = "Fecha Elaboracion")]
        public Nullable<System.DateTime> FECHA_ELABORACION_PRODUCTO { get; set; }
        [Display(Name = "Fecha Vencimiento")]
        public Nullable<System.DateTime> FECHA_VENCIMIENTO_PRODUCTO { get; set; }
        [Display(Name = "Precio Compra")]
        public Nullable<float> COMPRA_PRODUCTO { get; set; }
        [Display(Name = "Precio Venta")]
        public Nullable<float> VENTA_PRODUCTO { get; set; }
        [Display(Name = "Cantidad")]
        public Nullable<int> CANTIDAD_PRODUCTO { get; set; }
        [Display(Name = "Descripcion")]
        public string DESCRIPCION_PRODUCTO { get; set; }
        [Display(Name = "Tipo Producto")]
        public Nullable<int> ID_TIPO_PRODUCTO { get; set; }
        [Display(Name = "Sucursal")]
        public Nullable<int> ID_SUCURSAL_PRODUCTO { get; set; }
        [Display(Name = "Codigo Producto")]
        public string CODIGO_PRODUCTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura_producto> factura_producto { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_proveedor> producto_proveedor { get; set; }
    }
}
