//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class producto_proveedor
    {
        [Display(Name = "Producto")]
        public int ID_PRODUCTO { get; set; }
        [Display(Name = "Proveedor")]
        public int ID_PROVEEDOR { get; set; }
        public int ID_PROD_PROVE { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
