//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class telefono
    {
        public int ID_TELEFONO { get; set; }
        [Display(Name = "Telefono")]
        public string TELEFONO1 { get; set; }
        [Display(Name = "Tipo Telefono")]
        public Nullable<int> ID_TIPO_TELEFONO { get; set; }
        [Display(Name = "Persona")]
        public Nullable<int> ID_PERSONA_TELEFONO { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual tipo_telefono tipo_telefono { get; set; }
    }
}
