//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.rol_bd = new HashSet<rol_bd>();
            this.rol_servidor = new HashSet<rol_servidor>();
        }
    
        public int ID_USUARIO { get; set; }
        [Display(Name = "Nombre Usuario")]
        public string NOMBRE_USUARIO { get; set; }
        [Display(Name = "Password")]
        public byte[] CONTRASENA_USUARIO { get; set; }
        [Display(Name = "Tipo Usuario")]
        public Nullable<int> ID_TIPO_USUARIO { get; set; }
        [Display(Name = "Persona")]
        public Nullable<int> ID_PERSONA_USUARIO { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual tipo_usuario tipo_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_bd> rol_bd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol_servidor> rol_servidor { get; set; }
    }
}
